_wandb:
    value:
        cli_version: 0.27.0
        e:
            6pxd7skdfcwcqfrh1e4shqtyeg6tzihd:
                codePath: /home/jaume/ConquerX/Mis_apuntes/Pytorch/ejercicio_redes/Teleco_Customer_Churn/Teleco_Customer_Churn.ipynb
                codePathLocal: Teleco_Customer_Churn.ipynb
                email: jpalauserrano@gmail.com
                executable: /home/jaume/miniconda3/envs/torch/bin/python
                git:
                    commit: cda99904ed57f20f390e3b3c400d0d11877c7f82
                    remote: git@github.com:Jaume-Palau/Mis_apuntes.git
                host: ubuntujaume
                os: Linux-6.8.0-117-generic-x86_64-with-glibc2.35
                program: /home/jaume/ConquerX/Mis_apuntes/Pytorch/ejercicio_redes/Teleco_Customer_Churn/Teleco_Customer_Churn.ipynb
                python: CPython 3.11.14
                root: /home/jaume/ConquerX/Mis_apuntes/Pytorch/ejercicio_redes/Teleco_Customer_Churn
                startedAt: "2026-06-05T18:46:12.348109Z"
                writerId: 6pxd7skdfcwcqfrh1e4shqtyeg6tzihd
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 14
            "4": 3.11.14
            "5": 0.27.0
            "8":
                - 1
            "12": 0.27.0
            "13": linux-x86_64
batch_size:
    value: 16
dropout:
    value: 0.4
epochs:
    value: 100
hidden_size_1:
    value: 128
hidden_size_2:
    value: 16
lr:
    value: 0.0001
weight_decay:
    value: 0
