_wandb:
    value:
        cli_version: 0.27.0
        e:
            lfjim64u28u1mai5twx0zlgcg7vs9dbz:
                codePath: /home/jaume/ConquerX/Mis_apuntes/Pytorch/ejercicio_redes/Teleco_Customer_Churn/Teleco_Customer_Churn.ipynb
                codePathLocal: Teleco_Customer_Churn.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "100193038336"
                        used: "49411497984"
                email: jpalauserrano@gmail.com
                executable: /home/jaume/miniconda3/envs/torch/bin/python
                git:
                    commit: cda99904ed57f20f390e3b3c400d0d11877c7f82
                    remote: git@github.com:Jaume-Palau/Mis_apuntes.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-01654a73-47bd-4744-e01e-24b6fdeac28a
                host: ubuntujaume
                memory:
                    total: "33508593664"
                os: Linux-6.8.0-117-generic-x86_64-with-glibc2.35
                program: /home/jaume/ConquerX/Mis_apuntes/Pytorch/ejercicio_redes/Teleco_Customer_Churn/Teleco_Customer_Churn.ipynb
                python: CPython 3.11.14
                root: /home/jaume/ConquerX/Mis_apuntes/Pytorch/ejercicio_redes/Teleco_Customer_Churn
                startedAt: "2026-06-05T18:53:17.640883Z"
                writerId: lfjim64u28u1mai5twx0zlgcg7vs9dbz
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 14
            "4": 3.11.14
            "5": 0.27.0
            "8":
                - 1
            "12": 0.27.0
            "13": linux-x86_64
batch_size:
    value: 32
dropout:
    value: 0.2
epochs:
    value: 5
hidden_size_1:
    value: 64
hidden_size_2:
    value: 16
lr:
    value: 0.0001
weight_decay:
    value: 0
